### ISSUE TITLE
Object.assign not available in 0.10.x

### ISSUE THREAD

**Issue by GermanBluefox** [soef/soef#1]
This line https://github.com/soef/soef/blob/master/soef.js#L705 
does not allow to run the code on node.js 0.10.x.

May be extend it like this: 

```
if (!Object.assign) {
    var nObj = JSON.parse(JSON.stringify(options));
    nObj.type = nObj.type || obj.type;
    nObj._id = nObj._id|| obj._id;
} else {
    Object.assign(obj, options);
}
```

**Comment by soef** [comment]
is fixed in version 0..1.40

**Comment by GermanBluefox** [comment]
I am not sure, that your solution can copy something like:

```
{ 
    a: {
        b: 1
    },
    c: [1,2,3]
}
```

Array will be not copied it will be taken the same instance and not the copy.

**Comment by soef** [comment]
You are right. But it is the same then the original Object.assign does.

**Comment by soef** [comment]
To create a new object i'm using the clone function of the soef lib.
